config/routes.rb
Rails.application.routes.draw do
  root    'users#new'
  post    '/signup', to: 'users#create'
  get     '/login', to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  get     '/logout',  to: 'sessions#destroy'
  post     '/new_events', to: 'events#create'
  resources :users
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_guests, :foreign_key => :attendable_event_id
  has_many :guests, :through => :event_guests
  belongs_to :host, :class_name => "User"

  scope :upcoming_events, -> {where("date >= ?", Date.today)}
  scope :past_events, -> {where("date < ?", Date.today)}
end

app/models/event_guest.rb
class EventGuest < ApplicationRecord
belongs_to :guest, :class_name => "User"
belongs_to :attendable_event, :class_name => "Event"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :downcase_name

  has_many :event_guests, :foreign_key => :guest_id
  has_many :attendable_events, :through => :event_guests
  has_many :hosted_events, :foreign_key => :host_id, :class_name => "Event"

  private

  def downcase_name
    self.name.downcase!
  end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    unless current_user.nil?

      @event = current_user.hosted_events.build(params)
      if @event.save
        flash[:info] = "Event saved."
        redirect_to current_user
      end
    else
      render 'new'
    end
  end

  def index
    @all_upcoming_events = Event.upcoming_events
    @all_past_events = Event.past_events
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(name: params[:sessions][:name].downcase)
    if user
      log_in user
      redirect_to user
    else
      flash[:warning] = "No user by that name."
      render 'new'
    end
  end

  def new
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Signed In."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @hosted_events = @user.hosted_events
    @upcoming_events = @user.attendable_events.upcoming_events
    @past_events = @user.attendable_events.past_events
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<%= render "layouts/header" %>
<div class="col-md-6 col-md-offset-3">
  <h1> All upcoming events </h1>
    <ul class="events">
      <% @all_upcoming_events.each do |event| %>
        <li><%= link_to event.date, event%></li>
      <% end %>
    </ul>
</div>

<div class="col-md-6 col-md-offset-3">
  <h1> All past events </h1>
    <ul class="events">
      <% @all_past_events.each do |event| %>
        <li><%= link_to event.description, event%></li>
      <% end %>
    </ul>
</div>

app/views/events/new.html.erb
<%= render "layouts/header" %>
<%= form_for(:event, url: new_events_path) do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form_control'%>

  <%= f.label :date %>
  <%= f.date_field :date, class: 'form_control'%>
  <%= f.submit "Submit event", class: "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<%= render "layouts/header" %>
<div class="row">
  <h1>
    <%= @event.host.name %>
  </h1>
  <p>
    <%= @event.description %>
  </p>
  <p>
    <ul>
      <% @event.guests.each do |guest| %>
        <li><%= guest.name %> </li>
      <% end %>
    </ul>
  </p>
</div>

app/views/layouts/_form.html.erb
<%= form_for(yield(:record), url: yield(:url_path)) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form_control'%>
  <%= f.submit "Submit Name", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <% if current_user.nil? %>
          <li><%= link_to "Log in", login_path %></li>
        <% else %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Logout", logout_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= render "layouts/header" %>
<div class="col-md-6 col-md-offset-3">
  <h1> All users</h1>
    <ul class="users">
      <% @users.each do |user| %>
        <li><%= link_to user.name, user%></li>
      <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<%= render 'layouts/header' %>

<div class="welcome">
  <h1>Welcome to the private event builder</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form_control'%>
      <%= f.submit "Submit Name", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "layouts/header" %>
<div class="row">
  <aside class="col-md-4">
    <h1>
      <%= @user.name %>
    </h1>
  </aside>

  <div class="col-md-6 col-md-offset-3">
    <h1> Hosted Events </h1>
      <ul class="events">
        <% @hosted_events.each do |event| %>
          <li><%= link_to event.date, event%></li>
        <% end %>
      </ul>
  </div>

  <div class="col-md-6 col-md-offset-3">
    <h1> Upcoming Events </h1>
      <ul class="events">
        <% @upcoming_events.each do |event| %>
          <li><%= link_to event.date, event%></li>
        <% end %>
      </ul>
  </div>

  <div class="col-md-6 col-md-offset-3">
    <h1> Past Events </h1>
      <ul class="events">
        <% @past_events.each do |event| %>
          <li><%= link_to event.date, event%></li>
        <% end %>
      </ul>
  </div>

</div>